### ISSUE TITLE
Consumer Static Membership

### ISSUE THREAD

**Issue by bkowalk** [dashbitco/broadway_kafka#109]
I've been working on an interesting issue where our Kafka consumers get stuck in a rebalancing loop and stop consuming whenever our new docker images go live. Kubernetes rolls pods one at a time, so basically every launch the group never quite reaches a stable state to consume until all running pods have updated.

It looks like in Kafka 2.3, static membership was added (see a discussion [here](https://medium.com/bakdata/solving-my-weird-kafka-rebalancing-problems-c05e99535435#f2b5)), allowing a totally new consumer to take the place of the consumer that just went down, so long as they both specify the same `group.instance.id`. This could potentially entirely eliminate rebalancing during launches. Sounds really promising!

Saw an encouragement in the docs to mention any missing :brod options, and it seems like this might currently be supported by brod's `join_group` and `sync_group` requests (which both send in a member ID with their request, though it's not super clear to me from the docs how that works or if overriding would be wise). Anyway, I'd be super curious if anyone has already explored this!

**Comment by josevalim** [comment]
A pull request that Adds new options is welcome. You can see previous PRs as examples (it is a somewhat common occurrence). :)

**Comment by slashmili** [comment]
Hey! I see a problem implementing that in K8S environment. The blog post says


> If a consumer restarts for any reason, the group coordinator can assign the same partitions to the consumer without rebalancing everything.

But the problem is that how do you want to keep the IDs? As all the pods running a single deployment have identical settings. At least the way that we use it is to create a deployment and scale the deployment, something like : 
```
kubectl scale --replicas=10 deployments/my-app
```

Luckily for us most of the services that are consuming Kafka are not serving any web interface, therefore we were able to use [deployment strategy type](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) and Recreate. It shuts down all running pods and then start the new pods.

Nevertheless it would be awesometo support `static membership` in this project 🦾

**Comment by bkowalk** [comment]
Looked a bit deeper and it looks like the `memberId` that I was seeing in :brod is just an in-memory place to store the UUID passed back from the coordinator, not a way to pass in a custom `group.instance.id` in a join request that I thought. Seems that this won't be doable until :brod supports that. Going to close this for now and explore other options unless anyone feels like attempting this all the way down to the :brod level! Thank you both for the feedback in the meantime.

**Comment by slashmili** [comment]
@bkowalk shame!

BTW your problem of rebalancing might be related to this https://github.com/dashbitco/broadway_kafka/issues/98. Otherwise rebalancing shouldn't take that long–as long as each background job doesn't take long like 10 seconds.

**Comment by bkowalk** [comment]
Interesting! I suppose it's possible this could be affecting us, though it doesn't seem like it - the job in question takes around 300ms per message on the topic.

So at present, we have our session timeout set to 45 seconds. When I look into the logs during a launch, I see the consumers run through about 15 generations of rebalancing as our 4 pods roll one-at-a-time (each pod takes about 2 minutes from being taken down until it passes its health check). Sometimes the consumers are able to rebalance and keep running, but sometimes we see the coordinator stop everything as it rebalances, then something makes it wait the whole 45-second timeout and retry. Not sure, TBH, just definitely feels like it'd be avoided if the consumers just held onto their assignments!

Currently looking into `incremental cooperative rebalancing` as a possible way to minimize these effects.

**Comment by slashmili** [comment]
@bkowalk it's not as simple as that. maybe one messages takes 300ms but if there are 30 messages already waiting to be processed(buffered in PartitionDispatcher) it takes 300ms*30 to finish all the jobs and start joining the new generation–the producer does pulling and asking as well so you should add those time too

I've been trying to somehow monitor that and I think just now found the best way is to use telemetry #111

**Comment by bkowalk** [comment]
Great point. I don't see anywhere we're setting `max_bytes`, and you can fit quite a bit of data in the megabyte default. I'll do some exploring and see if that might be part of the delay before rebalance completes. Thanks for the tip!
