### ISSUE TITLE
Updates on the release date of the next version?

### ISSUE THREAD

**Issue by lfmatosm** [dashbitco/broadway_kafka#143]
Hi!

When are you planning to release the next version? Recently, a PR was merged adding support for `extra_sock_opts` for the `client_config` (https://github.com/dashbitco/broadway_kafka/pull/140). In my use-case, I need to use these options to configure a keep alive for the TCP connection.

Thanks for your work!

**Comment by josevalim** [comment]
Done!

**Comment by slashmili** [comment]
@josevalim if you accept and find it necessary, I'll be able to take care of some of the maintain for this repo.

**Comment by lfmatosm** [comment]
Thanks a lot @josevalim!

**Comment by josevalim** [comment]
Yes please, I would love it @slashmili! Let me know what you need.

**Comment by slashmili** [comment]
@josevalim nothing at the moment! I'm already getting notifications on the new issue and PRs. I'll start looking into them as quickly as they are created.
