### ISSUE TITLE
Implementing offset lag telemetry

### ISSUE THREAD

**Issue by David-Klemenc** [dashbitco/broadway_kafka#145]
Would it be possible to get lag offset in telemetry something like [kolt](https://github.com/moskyb/kolt) ?

**Comment by v0idpwn** [comment]
I think you should be able to use kolt with broadway_kafka as it uses brod

**Comment by David-Klemenc** [comment]
I can get producer names from Broadway:

```elixir
Broadway.producer_names(:kafka_test)
[:"kafka_test.Broadway.Producer_0"]
```

And from the logs I know that the client names look like
```elixir
:"Elixir.kafka_test.Broadway.Producer_0.Client"
```

But I have not found a way to get the client name from a Broadway api ? (I need it to call `:brod`)

```erlang
:brod.fetch_committed_offsets(:"Elixir.kafka_test.Broadway.Producer_0.Client", "test_group_id")
```

**Comment by josevalim** [comment]
I don’t believe there is one. A PR is welcome!

**Comment by josevalim** [comment]
Thanks! A PR to expose the client is still welcome (if there isn't one).
