### ISSUE TITLE
Does not compile with Erlang 27 due to transitive dependencies

### ISSUE THREAD

**Issue by mashton** [dashbitco/broadway_kafka#150]
### Issue
latest `broadway_kafka` uses `brod` 4.0.0, which pins `kafka_protocol` < 4.1.9.
Transitive dependency `port_compiler` is pinned at 1.14 in `crc32cer` 0.1.8
[pc 1.14 does not play nicely with Erlang 27](https://github.com/blt/port_compiler/issues/82)

`kafka_protocol` just release 4.1.9 which updates `crc32cer` to 0.11.1, which pins `pc` to 1.15

### Reproduce
Using erlang 27,
```
> mix new .
add {:broadway_kafka, "0.4.4"} to deps
> mix deps.get
> mix deps.compile
Result:
`Could not compile dependency :crc32cer`
```

### Fix?
[I've opened an issue in the brod repo](https://github.com/kafka4beam/brod/issues/596) to upgrade `kafka_protocol`. 
Once it does, `broadway_kafka` can update `brod`.

**Comment by josevalim** [comment]
Perfect. `mix deps.update brod` in your app should fix it then. Thanks!
