### ISSUE TITLE
Issues with lz4 compression

### ISSUE THREAD

**Issue by pcMarcos** [dashbitco/broadway_kafka#151]
Hey everyone, 

I'm having a problem when consuming events with LZ4 compression codec. 

When consuming events I have the `(UndefinedFunctionError) function :lz4b_frame.decompress` error. 

Already tried to install a lz4 lib, but didn't work. I think I'll need to overwrite the Compression module, as described here: https://hexdocs.pm/kafka_protocol/readme.html#compression-support

Has any of you faced this error before? If it's common, WDYT of having a step of documentation on how to process events lz4 compressed? 

`{"time":"2024-12-06T16:58:01.727Z","severity":"error","message":"GenServer ActivitiesApp.Kafka.Broadway.Producer_0 terminating\n** (UndefinedFunctionError) function :lz4b_frame.decompress/1 is undefined (module :lz4b_frame is not available)\n    :lz4b_frame.decompress(<<4, 34, 77, 24, 96, 64, 130, 7, 3, 0, 0, 241, 99, 154, 10, 0, 0, 0, 72, 50, 98, 102, 50, 100, 56, 48, 97, 45, 53, 97, 55, 48, 45, 52, 54, 101, 49, 45, 57, 98, 99, 50, 45, 101, 98, 53, 51, 56, 57, 52, ...>>)\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_compress.erl:91: :kpro_compress.do_decompress/2\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_batch.erl:199: :kpro_batch.do_decode/2\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_batch.erl:129: :kpro_batch.decode/2\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:787: :brod_utils.parse_fetch_rsp/1\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:615: :brod_utils.parse_rsp/1\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:485: :brod_utils.do_fetch/4\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:459: :brod_utils.fetch/4\n    (broadway_kafka 0.4.4) lib/broadway_kafka/producer.ex:621: BroadwayKafka.Producer.fetch_messages_from_kafka/3\n    (broadway_kafka 0.4.4) lib/broadway_kafka/producer.ex:346: BroadwayKafka.Producer.handle_info/2\n    (broadway 1.1.0) lib/broadway/topology/producer_stage.ex:223: Broadway.Topology.ProducerStage.handle_info/2\n    (gen_stage 1.2.1) lib/gen_stage.ex:2206: GenStage.noreply_callback/3\n    (stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6\n    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message: {:poll, {13, \"core.development.activities\", 0}}","metadata":{"error":{"initial_call":null,"reason":"** (UndefinedFunctionError) function :lz4b_frame.decompress/1 is undefined (module :lz4b_frame is not available)\n    :lz4b_frame.decompress(<<4, 34, 77, 24, 96, 64, 130, 7, 3, 0, 0, 241, 99, 154, 10, 0, 0, 0, 72, 50, 98, 102, 50, 100, 56, 48, 97, 45, 53, 97, 55, 48, 45, 52, 54, 101, 49, 45, 57, 98, 99, 50, 45, 101, 98, 53, 51, 56, 57, 52, ...>>)\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_compress.erl:91: :kpro_compress.do_decompress/2\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_batch.erl:199: :kpro_batch.do_decode/2\n    (kafka_protocol 4.1.9) /app/deps/kafka_protocol/src/kpro_batch.erl:129: :kpro_batch.decode/2\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:787: :brod_utils.parse_fetch_rsp/1\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:615: :brod_utils.parse_rsp/1\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:485: :brod_utils.do_fetch/4\n    (brod 4.3.1) /app/deps/brod/src/brod_utils.erl:459: :brod_utils.fetch/4\n    (broadway_kafka 0.4.4) lib/broadway_kafka/producer.ex:621: BroadwayKafka.Producer.fetch_messages_from_kafka/3\n    (broadway_kafka 0.4.4) lib/broadway_kafka/producer.ex:346: BroadwayKafka.Producer.handle_info/2\n    (broadway 1.1.0) lib/broadway/topology/producer_stage.ex:223: Broadway.Topology.ProducerStage.handle_info/2\n    (gen_stage 1.2.1) lib/gen_stage.ex:2206: GenStage.noreply_callback/3\n    (stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4\n    (stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6\n    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"}}}`

Thank you!

**Comment by josevalim** [comment]
Hi @pcMarcos, we don't have experience in this area, so a pull request is very welcome!

**Comment by pcMarcos** [comment]
It did work with `lz4b`. Thank you all for your help!
