### ISSUE TITLE
Kafka hosts standard notation

### ISSUE THREAD

**Issue by victorolinasc** [dashbitco/broadway_kafka#23]
Hi @msaraiva ! 

First of all, thanks a lot for your work here! 

I'd like to propose to also accept a `String.t()` as hosts. I am not an expert on Kafka tools, but it seems some tools accept that as it is easier to pass as an environment variable a dynamic number of values. The official libraries seem to support this too.

- [Java official library](https://docs.confluent.io/current/clients/java.html#initialization)
- [C++ official library](https://docs.confluent.io/current/clients/c_cpp.html#initialization)
- [Go official library](https://docs.confluent.io/current/clients/go.html#initialization)
- And so on...

I believe this is the most common way of initializing this for the ecosystem. I could open a PR if that is desired/wanted. It would be a very small code change for a nice developer happiness in my opinion. We would avoid doing something like this currently:

```elixir
# Something like
opts
|> Keyword.get(:brokers, "")
|> String.split(",", trim: true)
|> Enum.map(&String.split(&1, ":", trim: true))
|> Keyword.new(fn [key, val] -> {String.to_atom(key), String.to_integer(val)} end)
```

Once again, thanks for your work!

**Comment by josevalim** [comment]
I agree. We already had discussion here: https://github.com/dashbitco/broadway_kafka/pull/21

I think we should be generally moving to strings and away from tuples.

**Comment by victorolinasc** [comment]
All right! I've seen the discussion on #21 but it was more focused on not having to issue a `String.to_atom/1` I believe.

I'll try to open a PR tonight then.

Thanks
