### ISSUE TITLE
A way to access brod client

### ISSUE THREAD

**Issue by escobera** [dashbitco/broadway_kafka#26]
Hello there,
this is more a question than a issue. Is there a way to access the brod client that's started from broadway? 
I need to produce messages back to the same kafka topic that I'm reading with broadway, so starting another brod client process seems a bit overkill.

**Comment by chulkilee** [comment]
Since brod takes atom client id, you may pass the brod client id to broadway and use the same id from your module.

See (see https://github.com/dashbitco/broadway_kafka/blob/v0.1.2/lib/kafka_client.ex#L6 - you can pass the `client_id` option to broadway.

**Comment by josevalim** [comment]
Thanks for the help @chulkilee !

**Comment by escobera** [comment]
Hello @chulkilee , thanks a lot for the help!

I tried what you suggested, but was getting `{:error, :client_down}` errors from brod. So I noticed that event after I set up the client_id config it was still using an auto-generated name like this:

```
[info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.2162.0>, id: PropartesPje.Pje1i.BroadwayPje1i.Broadway.Producer_0.Client, mfargs: {:brod_client, :start_link, [[localhost: 9092], PropartesPje.Pje1i.BroadwayPje1i.Broadway.Producer_0.Client, []]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]]
```

My broadway config:
```elixir
def start_link(_opts) do
    Broadway.start_link(__MODULE__,
      name: __MODULE__,
      producer: [
        module:
          {BroadwayKafka.Producer,
           [
             hosts: Application.get_env(:propartes_pje, :kafka_host, localhost: 9092),
             group_id: "grupo-ex-propartes",
             client_id: :my_test_client,
             topics: ["postgres-pje"],
             client_config: Application.get_env(:propartes_pje, :kafka_client_config, [])
           ]},
        concurrency: 1
      ],
      processors: [
        default: [
          concurrency: 1
        ]
      ]
    )
  end
```

I think the client_id is being changed here:
https://github.com/dashbitco/broadway_kafka/blob/a1ee3390e67823135db7431f888231d7c5482947/lib/producer.ex#L171

**Comment by msaraiva** [comment]
Hi @escobera!

We could allow the user to set the `client_id` explicitly but I'm not sure that sharing it would be a good idea. The problem is that each producer process is responsible for the lifecycle of its own client so they should be considered "private" as you can't be sure when it would be available or whether it's being restarted or not. So I think it would be safer to keep them separate. I wouldn't worry much about performance either. It shouldn't add any significant overhead.

**Comment by escobera** [comment]
Gotcha, thanks for the help!
