### ISSUE TITLE
offset_reset_policy earliest resets offset to earliest on consumer reballance

### ISSUE THREAD

**Issue by gerbal** [dashbitco/broadway_kafka#27]
It appears the setting `offset_reset_policy: :earliest` is not working correctly (Or I have misunderstood how it should work). Consumer offsets are _always_ reset to earliest on app restart or when brod reballances partition assignments. 

In [BroadwayKafka.BrodClient.resolve_offset/4](https://github.com/dashbitco/broadway_kafka/blob/master/lib/brod_client.ex#L131) there is no condition where the consumer offset will be used when `:earliest` is used. 

I expect `offset_reset_policy: :earliest` should only reset to the earliest offset if no offset is found not at any time `consumer_offset > earliest_offset`

**Comment by josevalim** [comment]
Correct. Earliest is used only for the cases where you want to frequently start from the beginning. Latest is the one with the behavior you want. It is the latest committed.

**Comment by gerbal** [comment]
Then `offset_reset_policy: :earliest` has two effects
 - start new kafka consumers at earliest offset
 - reset all consumers to earliest offset any time brod receives any changes to partition assignments

While in `offset_reset_policy: :latest` only has one
 - start new kafka consumers at latest offset

What should I do if I want new consumers to start at the earliest offset but not reset to the earliest offset on app restart?

**Comment by josevalim** [comment]
If you don't have a committed offset, then that's how latest behaves. If you have a committed offset, then it is not possible with the current options, but I believe Kafka has APIs that allow you to reset it manually.

**Comment by v0idpwn** [comment]
@josevalim I believe this is not the way `:earliest` is expected to behave. Offset reset policies should be used only when the offset is undefined or when the kafka current_offset is expired.

We can see this in Confluent docs: https://docs.confluent.io/current/clients/consumer.html#offset-management and I'd say even broadway_kafka documentation for `offset_reset_policy` implies this:

> Defines the offset to be used when there's no initial offset in Kafka or if the current offset has expired. Possible values are :earliest or :latest. Default is :latest.

**Comment by josevalim** [comment]
You are correct. I misunderstood the docs. Thanks for the reference.

**Comment by josevalim** [comment]
In case someone wants to send a PR, it will be very appreciated too. :)

**Comment by v0idpwn** [comment]
I'll open one in a few minutes, I have fixed it locally :)

**Comment by victorolinasc** [comment]
Hey @josevalim ! Thanks for taking this in!

Can you release a minor version on hex? This would be greatly appreciated.

Thanks once again!

**Comment by msaraiva** [comment]
Hi @victorolinasc!

I'll release a new version today.

Thanks for your contribution!

**Comment by msaraiva** [comment]
@v0idpwn thanks for the PR! ❤️
