### ISSUE TITLE
How can I apply after fetch transformations to message list? (before sending it to batchers)

### ISSUE THREAD

**Issue by aviscasillas** [dashbitco/broadway_kafka#28]
Hi there!

First of all I just want to make clear that I've jumped into this project as part of a learning Elixir exercise I've been working on. So, even though I have a backend background and a bit of Kafka knowledge, I'm quite new into Elixir and it's my first time going through the Broadway library.

### A bit of context
I've been writing down a Kafka consumer, that is supposed to consume messages from a topic, which is configured with `compaction` (it's there to share the state of a specific entity across many services). 

The consumer I pretended to write, just takes messages from the topic and upserts or deletes records in a database, assuming the message `key` as the primary key of the entity.
I've written the consumer in a way that it sends `deletions` (tombstones), and `upserts` (messages with data) to separated batchers. 

### Now the problem
I wanted to apply a logical "compaction" to the given message list just after fetching it, so that I can take only the most recent message of each entity and discard the others that come in the same fetched batch.

**To put an example:**
If I receive `A1 | A2 | B1 | C1 | A3` in a fetch, I only want to process `B1 | C1 | A3`. So, I would aim for having a callback to apply `messages |> reverse |> uniq_by |> reverse` as a previous step before sending the different kind of messages to their corresponding batchers.

I've been playing around with the `Broadway` callbacks, and digging into the documentation, but I didn't get to find the proper way of making it work. So, I ended up forking this project and adding a configurable `after_fetch` callback that I use this way:
https://github.com/aviscasillas/elixir_kafka_consumer/blob/master/lib/elixir_kafka_consumer/handling/handler.ex#L24

As I'm totally new to this, I'm pretty sure that theres something I missed on how to achieve what I want with the actual implementation of this library, and I would be very thankful if someone could put some light on it 😅 .

Thanks!

**Comment by josevalim** [comment]
I think the issue is that you cannot assume that `A1 | A2 | B1 | C1 | A3` will come in same fetch. So while you can micro-optimize it for a batch of elements, you will need to be aware that the next batch may have a `A4` and that you run both `A3` and `A4`. If you are ok with this being an optimization and not a guarantee, then I believe this discussion here https://github.com/dashbitco/broadway/issues/172 would also allow you to do what you want.

**Comment by aviscasillas** [comment]
Thanks @josevalim! 😊 

> you cannot assume that A1 | A2 | B1 | C1 | A3 will come in same fetch.

Indeed not, but it's fine in my case as they come in order. The specific issue I'm having is that I'm processing tombstone messages in a `deletion`  batch, while I'm processing the others in an `upsert` batch, so I assume I cannot guarantee that they are processed in the right order, and I took the approach of just taking the most recent ones.

>  I believe this discussion here dashbitco/broadway#172 would also allow you to do what you want.

I totally missed that out sorry 🤦, and it's exactly what I'm looking for.

Thanks again!
