### ISSUE TITLE
Allow passing :connect_timeout to brod client

### ISSUE THREAD

**Issue by escobera** [dashbitco/broadway_kafka#31]
Hello,

I need to setup a longer timeout than the 5 seconds default one, brod allows this via the connect_timeout client option. 

Is it possible to allow this property to be set through broadway_kafka?

**Comment by josevalim** [comment]
Please send a pull request so we forward this option for the underlying brod connection. Thanks.

**Comment by escobera** [comment]
https://github.com/dashbitco/broadway_kafka/pull/32

**Comment by josevalim** [comment]
Thanks, closing in favor of the PR.
