### ISSUE TITLE
[Question] Obtain metadata in handle_message 

### ISSUE THREAD

**Issue by sweco-semtne** [dashbitco/broadway_kafka#36]
Hi! 
Thank you for a great library! 

I have a use case where we index incoming data by topic, partition, offset, timestamp where I think broadway would be a good fit. 
But I can't seem to find a way to get at the metadata at the message level?

**Comment by josevalim** [comment]
What have you tried? `message.metadata` should be enough.

**Comment by sweco-semtne** [comment]
I'm an idiot! :-) 
A typo later and a bad pattern match got me. 
Thanks for the quick reply!
