### ISSUE TITLE
Custom offset producer

### ISSUE THREAD

**Issue by D4no0** [dashbitco/broadway_kafka#55]
From documentation the only thing I could find about offset is:

> :offset_reset_policy - Optional. Defines the offset to be used when there's no initial offset in Kafka or if the current offset has expired. Possible values are :earliest or :latest. Default is :latest.

Is there a possibility to specify a custom offset from where the producer can start?

**Comment by josevalim** [comment]
As far as I know, not possible. I would check the docs for brod and if possible, a PR to support it here is welcome!

**Comment by D4no0** [comment]
It seems that the offset is set [here](https://github.com/dashbitco/broadway_kafka/blob/v0.2.0/lib/broadway_kafka/producer.ex#L282), I will try to inject a custom value here and see if it works.

**Comment by raphaklaus** [comment]
@D4no0 have you discovered something?

**Comment by D4no0** [comment]
Sadly, I gave up on using kafka, operational complexity is too high and the promises of the system are a little bit shady.
