### ISSUE TITLE
Broadway suspend pipeline

### ISSUE THREAD

**Issue by amacciola** [dashbitco/broadway_kafka#56]
Is there a way to suspend a Broadway kafka pipeline from ingesting data without having to fully kill the Genserver ?

**Comment by josevalim** [comment]
Try using `:sys.suspend` and `:sys.resume` on the producer names.

**Comment by v0idpwn** [comment]
@josevalim if I understand correctly, this wouldn't drain current messages, would it? Maybe we could support suspending on Broadway out of the box?

**Comment by josevalim** [comment]
You are correct. I also just realized that the better option is to call `GenStage.demand/2` on the producers. That will at least drain any demand *already requested*.

**Comment by v0idpwn** [comment]
Personally, I'm all in for this kind of feature to be available upstream on Broadway.

**Comment by josevalim** [comment]
Keep in mind that Broadway draining on shutdown pretty much sets GenStage.demand/2 to halt it, so it should be enough to achieve the desired behaviour. The issue with moving this to Broadway is that the behaviour can be drastically different between producers. For example in RabbitMQ we would need to ask the server to stop sending data and then ask it to resume. That's not necessary in none of the others.

**Comment by amacciola** [comment]
@josevalim so the best option to "halt + drain" the Broadway Kafka pipeline is to use the `GenStage.demand/2` call ?

**Comment by josevalim** [comment]
I *think* so but please try it out.

**Comment by amacciola** [comment]
@josevalim just to clarify you mean using 

`demand(stage(), :forward | :accumulate) :: :ok`

and setting the `mode` to `:accumulate` so it builds up the demand but does not forward it to the producers. Then when wanting to resume just change the `mode` back to `:forward`

**Comment by josevalim** [comment]
Yes.

**Comment by amacciola** [comment]
@josevalim it worked great !

i just did something simple like this for reference 

```
Broadway.producer_names(:pipeline_name)
|> Enum.each(fn producer ->
      GenStage.demand(producer, :accumulate)
  end)
```

```
Broadway.producer_names(:pipeline_name)
|> Enum.each(fn producer ->
      GenStage.demand(producer, :forward)
  end)
```

**Comment by josevalim** [comment]
Fantastic!

**Comment by amacciola** [comment]
@josevalim maybe i am also mis understanding. But how i thought this worked was 

- We have 1 Producer -> many Consumers. 
- When the GenStage pipeline is started (in this case the Broadway Kafka pipeline) the demand is forwarded from the Producer to the many Consumers. 
- Since the Consumers cannot fulfill the demand, since there is nothing in the Kafka topic, the demand for each consumer reaches its max and does not request any more from the Producer. 
- Then i change the Producer demand mode to be `:accumulate`. So it does not send any more demand to the Consumers if they ask for more.
- But there still exists the initial demand on all of the Consumers that was forwarded to each of them. So when data is pushed to Kafka, each consumer fetches the amount to satisfy their demand but does not go any further since the Producer will not give them any more in its current state

**Comment by josevalim** [comment]
I understand your scenario better. You are correct, if you suspend it, never resume it, then those messages will be there unless you also drain it.

If you want to suspend and never resume, why not terminate it?

In any case, we can allow setting the demand directly in this project. We only need to return it from the producer init callback. But if you know you will immediately start it as accumulated and never resume it, why start it in the first place?

**Comment by amacciola** [comment]
@josevalim i do want to resume it. A user may resume it whenever they choose.

however when they suspended it the ingested count was 0. So its very confusing to have the pipeline be in a suspended state and them see the count increase (increase by the initial demand)

**Comment by josevalim** [comment]
Suspending a pipeline takes time and it is only concluded when the pipeline drains all of its contents. So UI wise you should show as suspending until everything you eventually requested is consumed.

**Comment by amacciola** [comment]
@josevalim suspending a pipeline is pretty fast in my exp. By suspending i mean i am just changing the GenStage demand mode to `:accumulate` and waiting till all the current data in the consumers finishes processing.

We show the user in the UI a loading/progress bar when this is happening. 

The only issue here is that there was never any data ingested from kafka in this scenario. So nothing actually in the Consumers processing. So the user is not actually waiting for something to finish

**Comment by josevalim** [comment]
You already asked for the data upstream though. It cannot be suspended until that is cancelled or consumed somehow.

**Comment by amacciola** [comment]
@josevalim well that is what im asking i guess. If it should be the case that i am able to start the Pipeline with the option of being in `:accumulate` or `:forward` demand mode. This way if a Kafka Topic has no data to ingest. It should not send any data to the consumers.

I do feel like this is a problem i need to solve and less one for the library to implement. However do you know how i would flush the demand of the consumers ? or is that just not something that is possible

**Comment by josevalim** [comment]
Starting in accumulate should be doable. You need to return demand: :accumulate in the init producer tuple and we can support as an option in this library.

the one with consumer is more complicated because it needs coordination throughout the pipeline.

**Comment by amacciola** [comment]
@josevalim i will test with starting it in accumulate mode in the init and only changing it to forward if it meets my params
