### ISSUE TITLE
Question about :receive_interval and topology.

### ISSUE THREAD

**Issue by lud** [dashbitco/broadway_kafka#58]
I mainly use this library to get an easy setup instead of using brod directly, as I don't really understand the brod documentation.

My first question is: If I have concurrency set to `1` for the producer, and to `10` for the processors (and I have 10 partitions on all topics), is each Kafka message routed directly from a brod consumer to the processor ? Or are all messages bottlenecked to the producer before ?

Now, I saw that with the default `receive_interval`, a message sent to Kafka is not delivered directly, (I guess the delay is up to 2000ms because of the default value). What if I set this option to `100` or `1` ? It looks like it works great with low traffic. Would it flood the consumers with constant messages ? I've set `min_demand` to 1 because I want messages delivered as soon as they are available in Kafka but I am not even sure it has an impact.

I know it sounds that Kafka is not really the right tool here but I did not really have a choice.

Thank you.

**Comment by josevalim** [comment]
They go through the producer.

receive interval is the frequency to ping when the queue is empty. It doesn’t impact when the queue is full. It should not generate additional work to consumers.

**Comment by lud** [comment]
Ok José, thank you :)

**Comment by lud** [comment]
Hi again @josevalim 

I found that if y set the `concurrency` option at the _producer_ level to `5`, messages are delivered instantly. The default `1` has the long polling delays, even with `receive_interval` set to `1`. 

This happens when all topics are fully committed, (queues are empty), I produce a message to Kafka and expect a "response" message to be delivered to the Broadway producer. 

For now I keep it as-is but it feels weird to use multiple producers.

**Comment by lud** [comment]
@josevalim I tried an alternative implementation with Kaffe and I found the same behaviour, this time because of the `sleep_timeout` option for brod.

Though I guess broadway_kafka uses fetch instead of subscribers so I guess that is another problem.
