### ISSUE TITLE
Specific client_id for the :brod client

### ISSUE THREAD

**Issue by victorolinasc** [dashbitco/broadway_kafka#59]
I'd like to contribute a PR that would allow us to set the client_id of the `:brod` client. This is because when we have many instances of a service (say, k8s PODs) and you graph your consumer usage, I'd like to pass the instance name (POD name) as a prefix to the client_id to identify better possible discrepancies.

Would a PR here be welcomed? Haven't looked deep into the code yet but I believe that would be an extra client config option.

**Comment by josevalim** [comment]
Yes please!

**Comment by victorolinasc** [comment]
Done on #60
