### ISSUE TITLE
Integration tests instructions and CI

### ISSUE THREAD

**Issue by victorolinasc** [dashbitco/broadway_kafka#61]
From PR #60 I've noticed we are not actually running the integration tests on CI. Also, the instructions recommend installing Kafka locally which I'd say is not common practice IMHO.

From what I've seen on [Ecto](https://github.com/elixir-ecto/ecto/blob/v3.6.2/Earthfile), an Earthfile is used for integration testing. I think this could be applied here too or some other approach. In my experience, adding a docker-compose here would make the integration tests much easier and a similar approach would make the CI configuration easier too.

Would a PR with these changes be accepted? If yes, which approach would be preferred here?

**Comment by msaraiva** [comment]
Yeah, we should have the integration tests running on CI. A PR is certainly welcome here. 

Regarding the approach, I confess I don't have any particular preference so feel free to use Earthly, if you want.
