### ISSUE TITLE
Erlkaf as an optional kafka client

### ISSUE THREAD

**Issue by escobera** [dashbitco/broadway_kafka#62]
Hello there,

Would it be possible (and desireable) to offer an option to use erlkaf instead of brod as the underlying kafka client? We had to move to erlkaf from brod after some issues in our infrastructure and had to let go of broadway for that 😢 

I can try to come up with a PR for that if there's no problem.

I'm sorry if this is the wrong place to ask such questions, you can close the issue if that's the case.

**Comment by josevalim** [comment]
Hi @escobera! It may make sense but at the moment I am not sure if it is better as a separate library or by encapsulating the different behaviours in a client module. If you give it a try, please let us know how it goes. :)

**Comment by escobera** [comment]
Oh, I see what you mean. 

I noticed some of the main modules (i.e. [ BroadwayKafka.KafkaClient](https://github.com/dashbitco/broadway_kafka/blob/master/lib/broadway_kafka/kafka_client.ex) and [BroadwayKafka.Producer](https://github.com/dashbitco/broadway_kafka/blob/master/lib/broadway_kafka/producer.ex#L179)) depend explicitly on `:brod` types and/or behaviours. And since brod's and erlkaf's api differs violently this would be much harder to achieve then just creating another client module. I don't think I'm able to code this in a timely fashion, so I'll give it a try on my free time but will close this as not to polute the issue list. 

Thanks @josevalim =)
