### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by davydog187** [dashbitco/broadway_kafka#7]
It would be great to get the docs for `broadway_kafka` published. I know it is in a pre-release state, but it would be helpful for those who are trying to evaluate the library (such as my team).

Thank you for the great work on this, and for Hugo for letting me know about the progress here! 💯

**Comment by josevalim** [comment]
AFAIK, we can't publish the docs until we push the first release. We just need a bit more testing and feedback and it should be out soon!

**Comment by yammine** [comment]
Any update on this?

**Comment by josevalim** [comment]
We are working to release it soon, but we keep getting feedback, so just a
bit more time.
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*
