### ISSUE TITLE
Bump version to include bugfix

### ISSUE THREAD

**Issue by samuelpordeus** [dashbitco/broadway_kafka#81]
Hey 👋 – we bumped our version from 0.3.0 to 0.3.3 to solve the problem mentioned in #76, but when trying to deploy we realized we were having another bug (that was mentioned in #78).

we are currently pointing to 61bf8b7 to benefit from the bug fixes that were lovely done:
```
{:broadway_kafka, github: "dashbitco/broadway_kafka", ref: "61bf8b7"},
```

I was wondering if it's possible to bump the version officially to `0.3.4` and include that change.

sorry if it's not appropriate to ask this type of question here 😅

**Comment by josevalim** [comment]
v0.3.4 is out :)
