### ISSUE TITLE
Support for brod_gssapi and other custom brod sasl authenticators

### ISSUE THREAD

**Issue by ramonpin** [dashbitco/broadway_kafka#82]
As stated in the documentation the *BroadwayKafka.Producer* module is able to pass any configuration on the _client_config_ option down to the _:brod.start_client/3_.

Right now the code contains a validation that restricts the _sasl_ configuration options to the values:

- {:sasl, {:plain, user, password}}
- {:sasl, {:scram_sha_256, user, password}}
- {:sasl, {:scram_sha_512, user, password}}

But *:brod* also supports using authentication plugins as:

- {:sasl, {:callback :module, opts}}

For example you can use GSSAPI auth with kerberos by using the *brod_gssapi* plugin and the following client configuration:

- {:sasl, {:callback, :brod_gssapi, {:gssapi, keytab, principal}}}

Are you considering to allow this functionality?

**Comment by ramonpin** [comment]
From source code 'brod_client.ex':

```
  defp validate_option(:sasl, :undefined),
    do: {:ok, :undefined}

  defp validate_option(:sasl, value) do
    with {mechanism, username, password}
         when mechanism in [:plain, :scram_sha_256, :scram_sha_512] and
                is_binary(username) and
                is_binary(password) <- value do
      {:ok, value}
    else
      _value -> validation_error(:sasl, "a tuple of SASL mechanism, username and password", value)
    end
  end
```
I can try to make a MR adding the validation needed for the *callback* related tuple to that function but don't know if you expect any other problems down the stream.

**Comment by aravindanck** [comment]
We're also looking to have this option as part of Broadway Kafka. Just curious @ramonpin - which SASL mechanism are you trying to support?

**Comment by ramonpin** [comment]
@aravindanck our intention is to have support for the SASL_PLAINTEXT with GSSAPI at least. We probably will need to make several consecutive PRs to other erlang/kafka's ecosystem proyects.

**Comment by ramonpin** [comment]
Sorry guys some problems in other areas of the application leave me no time for this. 

@aravindanck great work from your side. Where you able to make it work with brod_gssapi library?

Hoping to contribute soon.

**Comment by aravindanck** [comment]
@ramonpin It should work for brod_gssapi library, as the validation check enables you to work with any SASL callback module. I tried this with a callback module built for a different SASL mechanism
