### ISSUE TITLE
Start offset for Broadway Kafka producer for a topic partition 

### ISSUE THREAD

**Issue by aravindanck** [dashbitco/broadway_kafka#87]
In the documentation, I couldn't find an option to supply start/begin offset for a given topic partition. Is it possible to supply it as init argument?

**Comment by josevalim** [comment]
We consume the offset specified by the group. I believe they are Kafka APIs for changing this offset and that's the route I propose going.

**Comment by aravindanck** [comment]
@josevalim Just to confirm my understanding - the feature is currently not available in broadway_kafka but Kafka APIs (Java) do support them. Is there a plan to bring it as part of broadway_kafka anytime soon?

**Comment by josevalim** [comment]
I meant via the CLI. :) you may also be able to do it with `:brod`, which is the Kafka client that we use.
