### ISSUE TITLE
Shutdown Pipeline Gracefully when Topic is removed

### ISSUE THREAD

**Issue by amacciola** [dashbitco/broadway_kafka#88]
Hello,

I was wondering what the best way to go about handling the shutdown of one of my Broadway Pipelines is, if the Topic its ingesting from is deleted while its still running.

I know when that happens currently it spits out a console error like

```
iex(cyn@10.50.0.35)1> 13:49:33.954 [error] GenServer :"ED-de2b90fa-c8b5-5cf7-834d-c62441245829-cab4c94c-ccb4-11ec-8fda-ee15ec8cad74Pipeline.Broadway.Producer_1" terminating
** (RuntimeError) cannot fetch records from Kafka (topic=residents partition=1 offset=2). Reason: :unknown_topic_or_partition
    (broadway_kafka 0.3.4) lib/broadway_kafka/producer.ex:537: BroadwayKafka.Producer.fetch_messages_from_kafka/3
    (broadway_kafka 0.3.4) lib/broadway_kafka/producer.ex:303: BroadwayKafka.Producer.handle_info/2
    (broadway 1.0.3) lib/broadway/topology/producer_stage.ex:229: Broadway.Topology.ProducerStage.handle_info/2
    (gen_stage 1.1.2) lib/gen_stage.ex:2117: GenStage.noreply_callback/3
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:poll, {1, "residents", 1}}
```

But then it will keep trying to restart a new Pipeline and rebase but there still wont be any Topic. So it will just fail over and over again. 

i tried placing a `Process.monitor()` on the PID of the BroadwayPipeline but i never see any "Terminated" or "Killed" messaged sent to it. 

Where should i looking to handle this ?

**Comment by amacciola** [comment]
It looks like no matter what the Producer will always catch and try and reconnect 

https://github.com/dashbitco/broadway_kafka/blob/06ed4352256d4e3de1f23659f44fea3a8f4471e9/lib/broadway_kafka/producer.ex#L384-L397

is there a way we could make this a configurable option or not for if a topic does not exist ?

**Comment by josevalim** [comment]
We can support a “shutdown_on_unknown_option” or similar. PR welcome!

**Comment by amacciola** [comment]
> We can support a “shutdown_on_unknown_option” or similar. PR welcome!

@josevalim okay when i get some free time i will work on it. In the mean time just coming up with a workaround in my applications. Just directly monitoring the Broadway Producers as well.
