### ISSUE TITLE
Proposal: Use per partition internal buffer

### ISSUE THREAD

**Issue by slashmili** [dashbitco/broadway_kafka#98]
> This is a fix of what I initially described at #92 

I'd like to purpose to change how we are keeping [buffers](https://github.com/dashbitco/broadway_kafka/blob/1eea41ebb559e5dab7749be7da98b24ac9c7dd09/lib/broadway_kafka/producer.ex#L255) internally in the producer. 

This proposal: 

* Increase concurrency.
* Speed up rebalancing time.
### How it works now

```mermaid
sequenceDiagram
    autonumber
    participant ProducerBuffer
    actor Producer
    actor GenStagePartitionDispatcher
    actor Consumer1
    actor Consumer2
    actor Consumer3

    Producer->>+Producer: Fetch Partition 0 data
    Producer->>-ProducerBuffer: insert 20 messages into internal queue
    Producer->>+Producer: Fetch Partition 1 data
    Producer->>-ProducerBuffer: insert 27 messages into internal queue
    Producer->>+Producer: Fetch Partition 2 data
    Producer->>-ProducerBuffer: insert 1 messages into internal queue

    Consumer1->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>ProducerBuffer: give me 5 messgaes
    ProducerBuffer->>Producer: Pop 5 messgaes
    Producer->>-GenStagePartitionDispatcher: hand 5 msgs over
    GenStagePartitionDispatcher->>+GenStagePartitionDispatcher: choose Consumer1 as a partition to hand partition 0 data
    GenStagePartitionDispatcher->>-Consumer1: give 5 messages 
    Consumer2->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>ProducerBuffer: give me 5 messgaes
    ProducerBuffer->>Producer: Pop 5 messgaes
    Producer->>-GenStagePartitionDispatcher: hand 5 msgs over
    GenStagePartitionDispatcher->>GenStagePartitionDispatcher: all partition 0 data, save it in internal buffer for Consumer1
    Consumer3->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>ProducerBuffer: give me 5 messgaes
    ProducerBuffer->>Producer: Pop 5 messgaes
    Producer->>-GenStagePartitionDispatcher: hand 5 msgs over
    GenStagePartitionDispatcher->>GenStagePartitionDispatcher: all partition 0 data, save it in internal buffer for Consumer1
```

It has impact on:
* concurrency: Consumer2 and Consumer3 are ready to accept data but are staying idle until GenStagePartitionDispatcher gets some data that can hand it over them
* rebalancing time: Imagine at this moment a assignment revoked is issued(caused by rebalancing) at this moment, we have to wait for Consumer1 to consume 15 messages before we can hand back control to brod to join the new generation.

### How the new setup will work: 

I have already have a "working" version https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd

I still needs to be tested and hash out some part that it was not clear to me but it's good enough to show you a demo!

Basically we have a [map of buffers](https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd#diff-972ac1f8e8719ed6755418a0e80ab45d206f244c2ace9a0454eaca9897690dc1R255) each time we fetch data from Kafka, we push it to it's own queue

```mermaid

sequenceDiagram
    autonumber
    participant ProducerBuffer
    actor Producer
    actor GenStagePartitionDispatcher
    actor Consumer1
    actor Consumer2
    actor Consumer3

    Producer->>+Producer: Fetch Partition 0 data
    Producer->>-ProducerBuffer: insert 20 messages into Partition0 queue
    Producer->>+Producer: Fetch Partition 1 data
    Producer->>-ProducerBuffer: insert 27 messages into Partition1 queue
    Producer->>+Producer: Fetch Partition 2 data
    Producer->>-ProducerBuffer: insert 1 messages into Partition2 queue

    Consumer1->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>-GenStagePartitionDispatcher: Pop 5 messgaes and hand it over (from which queue?)
    Consumer2->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>-GenStagePartitionDispatcher: Pop 5 messgaes and hand it over (from which queue?)
    Consumer3->>GenStagePartitionDispatcher: ask for 5
    GenStagePartitionDispatcher->>+Producer: handle_demand 5
    Producer->>-GenStagePartitionDispatcher: Pop 5 messgaes and hand it over (from which queue?)

```

But of course it's not easy! If you see 9, 12, 15 steps, how does Producer knows which queue to pop from!

In my change I came up with a logic that works ok: 
https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd#diff-972ac1f8e8719ed6755418a0e80ab45d206f244c2ace9a0454eaca9897690dc1R702-R712

It finds the first queue which has less than `max_demand` acks and the queue is not empty. There are also extra logics to rotate the queue that it's looking on each turn. you may ignore that for now.

It has impact on:
* concurrency: all the processors will get job to work on all the time. The estimating of whom needs seems work well. Even if it doesn't eventually in next few seconds as long there is a demand we hand over task 
* rebalancing time: Since PartitionDispatcher doesn't buffer extra events, when the rebalancing happens, the processors only need finish the job at hand. Producer doesn't give any event to PartitionDispatcher. Hence the rebalancing will be done in timely manner.

### Concurrency 

This [screenrecoding](https://github.com/slashmili/talks/blob/tmp-screen-recording/rec/show-case-per-partition-queue.mov) shows that on the panel left, using main branch, only events for partition 0 are being handled by process `0.269.0`. On the right, you'll see that the events for all partition are handled.

### Rebalancing 

This [screenrecoding](https://github.com/slashmili/talks/blob/tmp-screen-recording/rec/showcase-rebalancing-afer-a-node-joined.mov) shows that on the right panel(using the proposal approach). after the `rebalance_in_progress` happens, no more events are being processed because buffer of PartitionDispatcher is not overloaded by one partition events. The old node joins the new node in 10 seconds.

On the left it takes longer than expect(almost 1 minute). by the time it's ready, the timeout occurs and it starts a new generation. this will trigger rebalance on the new node and they'll keep taking each other off.

**Comment by josevalim** [comment]
Great job with the diagrams!

I think there may be a simpler solution to the routing. The PartitionDispatcher assumes somewhat even distribution of data, which is being violated here. So instead you can keep the buffer/queue per partition, then you store an index into which partition you must read from next, and you do so in cycles. You can do so with two changes:

1. Have map %{partition => queue}, which I believe you already do
2. Keep a ring to rate which partition to read next. This code can do it:

```
# Creates a new ring
defp new_ring([_ | _] = list), do: {list, []}

# Returns the {next_element_in_the_ring, ring}
defp next_ring({[], reversed}), do: next_partition({Enum.reverse(reversed), []})
defp next_ring({[head | tail], reversed}), do: {head, {tail, [head | reversed]}}
```

WDYT?

**Comment by slashmili** [comment]
Thanks!


I did kind use lame to make the ring 😬 
[here](https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd#diff-972ac1f8e8719ed6755418a0e80ab45d206f244c2ace9a0454eaca9897690dc1R540-R545) and [here](https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd#diff-972ac1f8e8719ed6755418a0e80ab45d206f244c2ace9a0454eaca9897690dc1R704-R707) 



I'd say still [checking acks count](https://github.com/slashmili/broadway_kafka/commit/4a4a69d1a51a5e43d717e5d2d12e7f6071c797bd#diff-972ac1f8e8719ed6755418a0e80ab45d206f244c2ace9a0454eaca9897690dc1R710) is important. In my example all the data were processed in 50ms but not the case in real life. It's the checking the acks that make sure we don't overload the Dispatcher.

**Comment by slashmili** [comment]
> Fair enough! I did remove the queue from my code and in the local env looks good enough to remedy the rebalancing as well. we can run it on prod when it's ready and monitor it.

Sorry I meant I did remove checks for ack and rebalancing was done quickly

**Comment by anoskov** [comment]
@slashmili great work! Can you tell me please, with your feature should I set producers count for each partition for max concurrency or I should set it to 1?

**Comment by slashmili** [comment]
> @slashmili great work! Can you tell me please, with your feature should I set producers count for each partition for max concurrency or I should set it to 1?

I haven't had a chance to work on the complete PR yet. When it's ready, you can choose whatever option suits you best.

**Comment by slashmili** [comment]
> Fair enough! I did remove the ~queue~ ack checking from my code and in the local env looks good enough to remedy the rebalancing as well. we can run it on prod when it's ready and monitor it.
> 

In the final implementation, it turns out that overloading PartitionDispatcher is still happening. I thought it solves the problem but there was a bug in my first code that the some demands were getting lost.
